### ISSUE TITLE
cp hosts file prompted for sudo password but failed due to permission denied

### ISSUE THREAD

**Issue by kundeng** [arashkaffamanesh/bonsai#2]
I still had to manually copy the hosts file.  Why?

**Comment by arashkaffamanesh** [comment]
does `sudo -i` work for you?

**Comment by kundeng** [comment]
sudo -i under mac?  Yes

I manually copied using sudo, it works fine.

**Comment by arashkaffamanesh** [comment]
make sure you can write to /etc/hosts with sudo, if /etc/hosts belongs to root, do a chown with your user id.
